### ISSUE TITLE
Atomicity issues in micro-ROS

### ISSUE THREAD

**Issue by Sdehnavi** [micro-ROS/rclc#21]
Hi,
I have been reading some parts of the reports in micro-ROS and it seems that because some kind of ARM processors do not support atomic operations, you have ignored the atomicity and have made a non-atomic implementation of the required functions.
By looking into the code, it seems that the atomic operations are used in Timer, Time and Context files.
What kind of problems may occur in terms of race condition if the SingleThreaded executor is used? I think there should be no race condition by default in that case?!
Thanks!

**Comment by ralph-lange** [comment]
Borja would know more about this. @jfm92, can you elaborate on this?

**Comment by Sdehnavi** [comment]
Thanks @ralph-lange for your comment.  @jfm92 It would be appreciated if you share your understandings on this issue.

**Comment by JanStaschulat** [comment]
@Sdehnavi @jfm92 @ralph-lange The rclc-executor is single threaded. If called from a single thread (e.g. main()) then I would not expect any race conditions. Reasoning: there are two phases of the rclc executor to consider. 

First phase: configuration. During this phase the rclc-executor uses rcl API to create nodes, timers, subscriptions etc. and dynamically allocates memory for a number of handles (timers, subscriptions). As this is single threaded, there should be no issue.

Second phase: during runtime, that is, if any of the spin-methods are called. Then, the rcl-API is used to create the wait_set and will call rcl_wait and rcl_take sequentially. Therefore, a single instance of the rclc executor never issues multiple calls to rcl_wait (or rcl_take) at the same time. So I do not expect any race conditions at runtime either. 

It is not intended, but possible, that you add handles (subscriptions, timers) after calling any of the spin-methods. Provided that sufficient number of handles were configured, the new handle will be considered at the next spin-method invocation. Again, if this is done from single thread, you are safe. If you call these methods (add_subscription, add_timer etc.) from multiple threads, you are asking for trouble. 

To my current understanding, because the XRCE DDS implementation for rcl is not thread safe, creating multiple rclc executors (which are using the same rcl-API) will not be thread safe. @jfm92 correct me, if I am wrong.

@Sdehnavi, What is your use-case?

**Comment by Sdehnavi** [comment]
@JanStaschulat Thanks for your explanation.
Yes I believe that in the single threaded scenario we are safe till the RMW layer and race conditioning may happen with regard to XRCE-DDS communication.
My use-case is a rover robot with some mixed critical application running in an isolated way.

**Comment by FranFin** [comment]
@Sdehnavi Hi! Thank you for your interest in micro-ROS. Notice that we’ll discuss the recent contributions and developments in the next [Embedded WG meeting](https://discourse.ros.org/t/ros-2-embedded-wg-meetings/15460). You’re invited to bring your micro-ROS related issue to this platform. We’ll be very happy to have you join us and discuss your questions with the community.
