### ISSUE TITLE
rclc_executor_spin vs rclc_executor_spin_some

### ISSUE THREAD

**Issue by eden-desta** [micro-ROS/rclc#69]
Hello again :) 

Another potential problem i noticed was running spin vs spin_some.

So I have a node that was able to run with rclc_executor_spin(&executor)
In hope of integrating multiple nodes I wanted to test the spin_some capability.

So i replaced the rclc_executor_spin(&executor) with
```
while(1) {
		rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100));
}
```

I looked at the source code for rclc_executor_spin, and this is exactly what it does, runs spin some in a while loop at 100ms timeout. I figured this should be a straight drop in.

However, it did not work at all. I have a feedback publisher in my node that publishes on subscription so i know i was able to successfully receive. 
I never was able to publish (or subscribe) with the spin some call, vs if i swapped out the rclc_executor_spin in again it would work.

Is there something I am missing here between these two calls, i feel as though it really should be a shoe in for one another but I'm definitely missing something. I have to be. 

This is how i am initialising everything:
```
allocator = rcl_get_default_allocator();
rclc_support_init(&support, 0, NULL, &allocator);
executor = rclc_executor_get_zero_initialized_executor();
rclc_executor_init(&executor, &support.context, 1, &allocator);
rclc_executor_add_subscription(&executor, &subscriber, &msg, &subscription_callback, ON_NEW_DATA);
```

Thank you a million! 
Look forward to your response!

**Comment by JanStaschulat** [comment]
@edesta-be 
Thanks for your feedback. the endless while loop with a spin_some should be the exact same behavior (assuming that ROS context is available during that time). I wrote some test cases in /tests/test_executor.cpp in which I used this kind of structure multiple times. 

What raised my attention was, "I am unable to run multiple nodes using two different sets of executors." 
Are you running that in one process or in multiple threads?
Could you share your source code or a minimal example demonstrating this problem?

Please note, that micro-ros can only be used for single threaded applications, if you create multiple nodes/subscriptions/executors/etc. in one process, this will work. If you have multiple threads in which you create multiple executors, then this will not work, because accessing the rcl layer in micro-ros is not thread-safe. Aka you can only access the methods from a single thread - so the same holds for all functions of rclc - library.

**Comment by eden-desta** [comment]
Hi!
Thanks for moving this issue @pablogs9 !

@JanStaschulat I actually found two problems with my implementation that allowed me to fix running multiple nodes. The first is you are right I was trying to run it in two different threads. 

Secondly, the app colcon file needed to be updated with the number of nodes, publishers and subscribers. I wasnt aware that file needed to define the maximum along with us determining the number of items the executor is hosting per executor. So i was able to get it to work by updating those values and making it a single threaded application!

Thank you all!

In what capacity can I support to perhaps document this for anyone else that might find themselves in the same scenario?

**Comment by JanStaschulat** [comment]
Hi @edesta-be, 
indeed the multi-threaded problem and the configuration of maximum number of pub/sub etc. is a common issue. We should document this more prominently. I could add a note in the header file of rclc executor that spin-functions shall only be called from one single thread, if used in micro-ros.

thank you very much for your feedback. It would be great, if you could document this here. 
Later on, we could then compile an FAQ on micro-ros.github.io where user can search for common errors and solutions. 

By the way, the current work-around is to have just a single threaded access to the executor. But of course you can have multiple threads in your application. Then you communicate data via condition variables and a mutex lock from the "ros 2 thread" to all other threads. 

I am currently working on a multi-threaded version of the rclc-executor, in which every subscription/timer etc. is executed in its own thread (and you could assign a priority to it, if you want).
